/* AI champion roster — game/content/ai.js
   Add new champions by appending to this object. Rotation pools live in
   game/registry.js (NORMAL_POOL / BOSS_POOL). */
Object.assign(AIS, {
  // curve: how much this champion bends its returns in flight (0 = straight, 1 = heavy curve).
  wall:     { icon: '🧱', name: 'The Wall',     title: 'UNBREAKABLE',      color: '#4ade80', speed: 360, react: 0.24,  error: 40,  predict: false, paddleMult: 1.70, aim: 0.0,  curve: 0.0,  personality: 'defense',    ability: 'tank',    abilityName: 'Passive — Fortress',  abilityDesc: 'A towering panel that smothers angles. Slow, but its reach is enormous.' },
  viper:    { icon: '🐍', name: 'The Viper',    title: 'LIGHTNING STRIKE', color: '#facc15', speed: 620, react: 0.10, error: 14,  predict: true,  paddleMult: 0.75, aim: 0.35, curve: 0.15, personality: 'aggressive', ability: 'surge',   abilityName: 'Surge — Overdrive',    abilityDesc: 'Every 6 seconds it hits overdrive: movement speeds up for 1.2s, then it overcommits — punish the miss.' },
  diviner:  { icon: '🔮', name: 'The Diviner',  title: 'READS YOUR MOVE',  color: '#a78bfa', speed: 560, react: 0.03,  error: 3,   predict: true,  paddleMult: 1.00, aim: 0.9,  curve: 0.85, personality: 'tricky',     ability: 'diviner', abilityName: 'Counter — Psychic Spin', abilityDesc: 'Predicts full bounces and spins returns against your movement. Fake it out by feinting.' },
  smasher:  { icon: '💥', name: 'The Smasher',  title: 'DEMOLITION',       color: '#fb923c', speed: 600, react: 0.07,  error: 10,  predict: true,  paddleMult: 1.00, aim: 0.4,  curve: 0.30, personality: 'aggressive', ability: 'smasher', abilityName: 'Power Hits — Detonation', abilityDesc: 'Every smash adds +36 speed to the ball. Rallies get violent fast.' },
  glacier:  { icon: '🧊', name: 'The Glacier',  title: 'CRYOGENIC ZONE',   color: '#7dd3fc', speed: 480, react: 0.14,  error: 18,  predict: true,  paddleMult: 1.25, aim: 0.2,  curve: 0.0,  personality: 'defense',    ability: 'glacier', abilityName: 'Aura — Frozen Fingers',   abilityDesc: 'Its cold aura halves your paddle speed. Big reach, glacial pace, cold hands.' },
  gambler:  { icon: '🎲', name: 'The Gambler',  title: 'ALL OR NOTHING',   color: '#fbbf24', speed: 540, react: 0.07,  error: 14,  predict: true,  paddleMult: 1.00, aim: 0.5,  curve: 0.55, personality: 'eccentric',  ability: 'gamble',  abilityName: 'Gamble — Coin Flip',     abilityDesc: 'Every 4 seconds it rolls the dice: half the time it teleports onto the ball, half the time it freezes. Unpredictable.' },
  knight:   { icon: '🛡️', name: 'The Knight',   title: 'IRON VOW',         color: '#93c5fd', speed: 515, react: 0.08,  error: 12,  predict: true,  paddleMult: 1.15, aim: 0.3,  curve: 0.15, personality: 'defense',    ability: 'parry',   abilityName: 'Parry — Counter',       abilityDesc: 'Every 6 seconds it raises a shield for 1.2s: hits during the parry rocket back at +60 speed.' },
  siren:    { icon: '🧜', name: 'The Siren',    title: 'HYPNOTIC',         color: '#f9a8d4', speed: 575, react: 0.06,  error: 9,   predict: true,  paddleMult: 0.95, aim: 0.6,  curve: 0.60, personality: 'tricky',     ability: 'lure',    abilityName: 'Lure — Hypnosis',       abilityDesc: 'Every 7 seconds it clouds your mind: your paddle controls invert for 1.8s.' },
  falcon:   { icon: '🦅', name: 'The Falcon',   title: 'EYES ON THE PREY', color: '#fca5a5', speed: 650, react: 0.045, error: 7,   predict: true,  paddleMult: 0.85, aim: 1.0,  curve: 0.45, personality: 'aggressive', ability: 'hunt',    abilityName: 'Hunt — Open Court',      abilityDesc: 'It always finds the open space: every return is aimed at the spot you are NOT covering.' },
  tortoise: { icon: '🐢', name: 'The Tortoise', title: 'UNMOVABLE',        color: '#86efac', speed: 280, react: 0.16,  error: 24,  predict: false, paddleMult: 2.00, aim: 0.1,  curve: 0.0,  personality: 'defense',    ability: 'shell',   abilityName: 'Shell — Weak Spot',      abilityDesc: 'A colossal, near-unmovable panel — but every 5 seconds it withdraws into its shell, shrinking for 1s. Strike then.' },
  bastion:  { icon: '🏰', name: 'The Bastion',  title: 'IRON CURTAIN',     color: '#9ad0ff', speed: 380, react: 0.13,  error: 14,  predict: true,  paddleMult: 1.45, aim: 0.1,  curve: 0.0,  personality: 'defense',    ability: 'bastion', abilityName: 'Wall — Iron Curtain',    abilityDesc: 'Every 6 seconds it raises an energy wall that catches ONE ball that slips past its panel. Pure defense.' },
  echo:     { icon: '👥', name: 'The Echo',     title: 'TWICE THE TROUBLE', color: '#7dd3fc', speed: 500, react: 0.065, error: 10,  predict: true,  paddleMult: 0.90, aim: 0.4,  curve: 0.70, personality: 'tricky',     ability: 'echo',    abilityName: 'Echo — Afterimage',      abilityDesc: 'Every 6 seconds it leaves a ghost of itself that returns the ball at double angle. Aim where it is NOT.' },
  zephyr:   { icon: '🌬️', name: 'The Zephyr',  title: 'WHIRLWIND',        color: '#a5f3fc', speed: 540, react: 0.055, error: 8,   predict: true,  paddleMult: 0.85, aim: 0.7,  curve: 0.85, personality: 'tricky',     ability: 'gust',    abilityName: 'Gust — Wind Spirals',    abilityDesc: 'Every 7 seconds it summons a gust that wobbles every ball in flight for 2.5s. Read the air.' },
  ogre:     { icon: '👹', name: 'The Ogre',     title: 'BLOODRAGE',        color: '#f87171', speed: 600, react: 0.06,  error: 9,   predict: true,  paddleMult: 1.10, aim: 0.5,  curve: 0.40, personality: 'aggressive', ability: 'rage',    abilityName: 'Rage — Bulldoze',        abilityDesc: 'Every 7 seconds it enters a rage for 3s: 2.2× movement and every hit carries +30 speed with rough spin.' },
  phantom:  { icon: '👻', name: 'The Phantom',  title: 'SINISTER',         color: '#c084fc', speed: 680, react: 0.045, error: 5,   predict: true,  paddleMult: 0.90, aim: 0.7,  curve: 0.65, personality: 'eccentric',  ability: 'phantom', abilityName: 'Phase — Intangible',       abilityDesc: 'Every 5 seconds it phases out and ghosts toward the ball for 1.2s — your shots pass straight through.' },
  weaver:   { icon: '🕸️', name: 'The Weaver',  title: 'WEB OF DOOM',      color: '#f0abfc', speed: 530, react: 0.12,  error: 15,  predict: true,  paddleMult: 1.10, aim: 0.5,  curve: 0.55, personality: 'eccentric',  ability: 'weaver',  abilityName: 'Hive — Swarm',           abilityDesc: 'Every 8 seconds it spins TWO new balls into play (up to 4). Chaos in motion.' },
  mirror:   { icon: '🪞', name: 'The Mirror',   title: 'REFLEXION',        color: '#f472b6', speed: 605, react: 0.055, error: 8,   predict: true,  paddleMult: 1.00, aim: 0.8,  curve: 0.95, personality: 'tricky',     ability: 'mirror',  abilityName: 'Reflection — Magnified', abilityDesc: 'Its returns double their angle AND carry heavy spin. Wild curves that are brutal to read.' },
  titan:    { icon: '🗿', name: 'The Titan',    title: 'MOUNTAIN',         color: '#b0b7c9', speed: 470, react: 0.09,  error: 9,   predict: true,  paddleMult: 1.25, aim: 0.5,  curve: 0.45, personality: 'aggressive', ability: 'quake',   abilityName: 'Quake — Seismic Slam',   abilityDesc: 'Every 7 seconds it slams the arena: shake, +40 speed AND wild spin on every ball. Every 10s it charges a SEISMIC POWER SHOT.' , charge: 10 },
  warlock:  { icon: '🧙', name: 'The Warlock',  title: 'CURSEBRINGER',     color: '#a3e635', speed: 555, react: 0.07,  error: 10,  predict: true,  paddleMult: 1.05, aim: 0.6,  curve: 0.55, personality: 'eccentric',  ability: 'hex',     abilityName: 'Hex — Cursed Grip',      abilityDesc: 'Every 6 seconds it curses your paddle (30% shorter & slower). Every 12s it charges a CURSED BOLT.' , charge: 12 },
  archon:   { icon: '⚡', name: 'The Archon',   title: 'STORM OF FATE',    color: '#fde047', speed: 560, react: 0.045, error: 6,   predict: true,  paddleMult: 1.15, aim: 0.7,  curve: 0.65, personality: 'eccentric',  ability: 'storm',   abilityName: 'Storm — Lightning',      abilityDesc: 'Every 8 seconds it summons a storm: every ball gains +30 speed and wild spin, and its electrified returns add +50. Every 11s it charges a THUNDER POWER SHOT.', charge: 11 },
  leviathan:{ icon: '🌊', name: 'The Leviathan', title: 'DEEP TIDE',       color: '#60a5fa', speed: 540, react: 0.06,  error: 8,   predict: true,  paddleMult: 1.30, aim: 0.6,  curve: 0.75, personality: 'eccentric',  ability: 'tide',    abilityName: 'Tide — Undertow',        abilityDesc: 'Every 9 seconds a tide drags every ball sideways for 3s, swapping direction each time. Every 13s it charges a TIDAL POWER SHOT.', charge: 13 },
});
